### ISSUE TITLE
多处编译出错

### ISSUE THREAD

**Issue by Maicius** [snowy-dong/react-hot-web#1]
npm run start 多处报错，但报错都是：  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'，网上多处搜索但是没找到解决方案
Jetbrain Webstrom打开项目提示以下错误：
1.karma.conf.js提示module is not define;
2.多个js文件在导入库时 import失败，提示 import is only available in ES6, 将setting 里语言改为ES6依然报这个错误。
最终打开网站发现多处效果丢失。
刚接触React不久，非常喜欢这个网站效果，希望能帮忙指出错误原因

**Comment by snowy-dong** [comment]
样式文件丢失，重新修改了webpack配置文件

**Comment by Maicius** [comment]
非常感谢
